/*
 * @Author: qintl
 * @File: 菜单 可选Icon列表
 * @Date: 2018-04-18 11:22:55
 * @Last Modified by: qintl
 */

const icons = [
  {
    prefix: 'fa',
    list: [
      'home',
      'address-book-o',
      'asterisk',
      'balance-scale',
      'bank',
      'line-chart',
      'area-chart',
      'pie-chart',
      'bar-chart',
      'book',
      'bookmark',
      'bookmark-o',
      'braille',
      'building',
      'calculator',
      'calendar',
      'calendar-o',
      'calendar-check-o',
      'cc',
      'certificate',
      'clone',
      'cloud',
      'credit-card',
      'credit-card-alt',
      'cube',
      'cubes',
      'crosshairs',
      'database',
      'desktop',
      'exchange',
      'file-audio-o',
      'file-photo-o',
      'file-video-o',
      'film',
      'flag',
      'flag-o',
      'flag-checkered',
      'gift',
      'gears',
      'graduation-cap',
      'hand-pointer-o',
      'handshake-o',
      'hourglass-1',
      'hourglass-end',
      'image',
      'inbox',
      'industry',
      'institution',
      'key'
    ]
  },
  {
    prefix: 'B5D',
    list: [
      'toubiao1',
      'project2',
      'xiangmu',
      'jindu',
      'zhiliang',
      'Workbench',
      'danfangchengben',
      'projectlist',
      'enterprise',
      'quality',
      'tech',
      'safety',
      'progress',
      'operating',
      'authorization',
      'enterprise1',
      'dictionary',
      'organization',
      'member',
      'objective',
      'verification',
      'chanzhitianbao',
      'jindutianbao',
      'xiangmuxinxi',
      'date',
      'shandian',
      'fujian',
      'daochu',
      'zhihang',
      'detail',
      'shuoming',
      'shichang2',
      'xitongshezhi',
      'Push',
      'tianbao',
      'ic-xiangmutezheng',
      'chanzhi',
      'index',
      'bigscreen',
      'ziyuan',
      'lingdao',
      'anquanmao1',
      'jingyingjinjieselect',
      'geps',
    ]
  }
]

export default icons
